<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';
$user = require_role('admin');
$summary = db()->query("SELECT COUNT(*) booking_count,COALESCE(SUM(quantity),0) tickets_sold,COALESCE(SUM(CASE WHEN status='confirmed' AND payment_status='paid' THEN total_amount ELSE 0 END),0) revenue FROM bookings")->fetch();
$eventReport = db()->query("SELECT e.title,u.name organizer,c.name category,COUNT(b.id) bookings,COALESCE(SUM(CASE WHEN b.status='confirmed' THEN b.quantity ELSE 0 END),0) tickets,COALESCE(SUM(CASE WHEN b.status='confirmed' AND b.payment_status='paid' THEN b.total_amount ELSE 0 END),0) revenue FROM events e JOIN users u ON u.id=e.organizer_id JOIN categories c ON c.id=e.category_id LEFT JOIN bookings b ON b.event_id=e.id GROUP BY e.id ORDER BY revenue DESC,e.event_date ASC")->fetchAll();
$roleCounts = db()->query('SELECT role,COUNT(*) total FROM users GROUP BY role')->fetchAll();
$title='Reports'; $bodyClass='admin-page admin-workspace'; $flashMessages=consume_flash();
require dirname(__DIR__).'/includes/header.php';
?>
<section class="plain-page-head"><div class="container plain-page-head-inner"><div><span class="plain-page-label">Performance</span><h1>Reports</h1><p>Review booking, revenue, event, and account information.</p></div><div class="plain-page-actions"><button class="btn btn-secondary" type="button" onclick="window.print()">Print report</button></div></div></section>
<section class="admin-page-content"><div class="admin-metrics admin-report-metrics"><article class="admin-metric-card"><span class="admin-metric-label">Bookings</span><strong><?= number_format((int)$summary['booking_count']) ?></strong><small>All booking records</small></article><article class="admin-metric-card"><span class="admin-metric-label">Tickets sold</span><strong><?= number_format((int)$summary['tickets_sold']) ?></strong><small>Reserved ticket quantity</small></article><article class="admin-metric-card admin-metric-revenue"><span class="admin-metric-label">Paid revenue</span><strong>LKR <?= number_format((float)$summary['revenue'],2) ?></strong><small>Confirmed payments</small></article></div>
<div class="admin-bookings-panel"><div class="admin-panel-heading"><div><span class="admin-eyebrow">Event performance</span><h2>Event report</h2></div></div><div class="admin-table-wrap"><table><thead><tr><th>Event</th><th>Organizer</th><th>Category</th><th>Bookings</th><th>Tickets</th><th>Revenue</th></tr></thead><tbody><?php foreach($eventReport as $row): ?><tr><td><strong><?= e($row['title']) ?></strong></td><td><?= e($row['organizer']) ?></td><td><?= e($row['category']) ?></td><td><?= number_format((int)$row['bookings']) ?></td><td><?= number_format((int)$row['tickets']) ?></td><td>LKR <?= number_format((float)$row['revenue'],2) ?></td></tr><?php endforeach; ?></tbody></table></div></div><div class="admin-role-summary"><?php foreach($roleCounts as $role): ?><div><strong><?= number_format((int)$role['total']) ?></strong><span><?= e(ucfirst($role['role'])) ?> accounts</span></div><?php endforeach; ?></div></section>
<?php require dirname(__DIR__).'/includes/footer.php'; ?>
